### ISSUE TITLE
Tile ID map ignores gaps for sections that contain multiple disconnected components

### ISSUE THREAD

**Issue by aloejhb** [fmi-basel/gfriedri-em-alignment#11]
For a section that contains multiple disconnected components (See in picture), the current [compute_tile_id_map](https://github.com/fmi-basel/gfriedri-em-alignment/blob/0ae01910648d51bdc33f68c171aebf30dddcbb4c/src/sbem/record/SectionRecord.py#L97) function will generate a tile_id_map that ignores the gaps between the components.
For example, the section (s1161) shown in picture will have a tile_id_map as follows:
```
array([[456,  -1,  -1],
       [484, 485,  -1],
       [ -1, 513, 514],
       [ -1, 541, 542],
       [624, 625, 626],
       [652, 653, 654],
       [680, 681, 682],
       [708, 709, 710],
       [ -1, 737, 738],
       [ -1,  -1, 766]])
```
![example_section_with_multiple_components](https://user-images.githubusercontent.com/19688778/172832082-0397c713-c7d0-4ff7-8910-49a538972ee0.png)
This will result in SOFIMA computing overlaps between actually not overlapping tiles in the stitch_rigid.compute_coarse_offsets step. Thus leading to inf offset values.

**Comment by tibuch** [comment]
Expected would be:
```
array([[456,  -1,  -1],
       [484, 485,  -1],
       [ -1, 513, 514],
       [ -1, 541, 542],
       [ -1, -1, -1],
       [ -1, -1, -1],
       [624, 625, 626],
       [652, 653, 654],
       [680, 681, 682],
       [708, 709, 710],
       [ -1, 737, 738],
       [ -1,  -1, 766]])
```
?

**Comment by tibuch** [comment]
Is the tile-size for an experiment constant?

**Comment by aloejhb** [comment]
> Expected would be:
> 
> ```
> array([[456,  -1,  -1],
>        [484, 485,  -1],
>        [ -1, 513, 514],
>        [ -1, 541, 542],
>        [ -1, -1, -1],
>        [ -1, -1, -1],
>        [624, 625, 626],
>        [652, 653, 654],
>        [680, 681, 682],
>        [708, 709, 710],
>        [ -1, 737, 738],
>        [ -1,  -1, 766]])
> ```
> 
> ?

Yes, that would be the expected results

**Comment by aloejhb** [comment]
> Is the tile-size for an experiment constant?

Normally, the tile-size will not be changed throughout an experiment, or at least throughout a block. There has been a stack in which the tile-size were changed, but this was rare, and we could treat the two blocks with different tile-size separately as two experiments.

**Comment by tibuch** [comment]
I will try to get it done without extra parameters, but if it turns out to be too complicated I will get back to this and we can improve it later.

**Comment by tibuch** [comment]
The above mentioned commit should fix the issue. I added a test here: https://github.com/fmi-basel/gfriedri-em-alignment/blob/98de6db217640bdec86b5d52455dcc73a1286675/tests/record/test_SectionRecord.py#L127

I will now address issue #14 by saving the `tile_id_map` as json file. Which makes them human readable and editable. After that you could continue testing with real data.

**Comment by aloejhb** [comment]
This issue was fixed nicely by the new commit. Thank you very much @tibuch !
There was a tiny bug that section.save_dir is None when loading a section. The quick fix is here [03fea12](https://github.com/fmi-basel/gfriedri-em-alignment/commit/03fea12bb4b6003eea4166ff5a5badd7ed67b5df)

**Comment by tibuch** [comment]
Thanks for the fix! Will take it and then merge everything into main.

**Comment by aloejhb** [comment]
This looks very cool. I will try to test it later. Thanks Tim-Oliver!

Tim-Oliver Buchholz ***@***.***> 于 2022年6月17日周五 上午11:04写道：
