### ISSUE TITLE
Save newly added block without saving the entire experiment

### ISSUE THREAD

**Issue by aloejhb** [fmi-basel/gfriedri-em-alignment#15]
For the on-the-fly stitching, the user will first parse and save some initial blocks. Afterwards, a new block will be acquired by the microscope. Then the user would need to parse and save the newly added block.
Currently, the [Experiment.save()](https://github.com/fmi-basel/gfriedri-em-alignment/blob/85912fdc34fcff67fea01e1824b539272d863994/em_alignment/sbem/experiment/Experiment.py#L81) will save all blocks, including the previously saved blocks. This will cost extra time and can overwrite the user-modified tile_id_map.json.
Therefore, it would be nice to have a function to allow saving an individual block. With this function, the user can do the following:
``` Python
# Load experiment
exp = Experiment()
exp.load(exp_dir)

# Add a Block
tile_width = 3072
tile_height = 2304
tile_overlap = 220
exp.parse_block(data_dir, block_name, "g0001", 11.0,
                tile_width, tile_height, tile_overlap)

# Save the added block
exp.save_block(block_name)
```

**Comment by aloejhb** [comment]
I wrote a function in [Experiment.py](https://github.com/fmi-basel/gfriedri-em-alignment/blob/ba86afe83c34c685619061d11bb30d7381c18c67/src/sbem/experiment/Experiment.py#L195), which seems to work. Not sure whether this is consistent with the code structure and whether I need to write a test for this.

**Comment by tibuch** [comment]
Thanks! Will take a look and merge into main.
