### ISSUE TITLE
Add acquisitions to a sample in a permuted order

### ISSUE THREAD

**Issue by aloejhb** [fmi-basel/gfriedri-em-alignment#29]
For example, I have 3 acquisitions for a sample, 
acquisition1 (acq1) contains sections from 1 to 100,
acquisition2 (acq2) contains sections from 101 to 200,
acquisition3 (acq3) contains sections from 201 to 300.

When I add sections, acq1 and acq3 were added successfully. Acq2 needs to be added after acq1 and acq3 because I need to solve some issue in acq2 metadata manually.

Then em-alinment shows me an error if I add acq2 after acq1 and acq3 are already in the sample:
``` 
File "/tungstenfs/scratch/gfriedri/hubo/em_alignment/packages/gfriedri-em-alignment/src/sbem/record/Sample.py", line 56, in add_section
    raise RuntimeError("This should never happen.")
RuntimeError: This should never happen.
```
It seems that it is checking whether the added section is outside the existing section range at this [line](https://github.com/fmi-basel/gfriedri-em-alignment/blob/6c9ba30e40c44683318243be6b035bd6d2ea3124/src/sbem/record/Sample.py#L56). This will fail if the added section is inside the existing section range.
Would it be safe to remove this checking or the removal will cause some issues downstream?

**Comment by tibuch** [comment]
I added this `RuntimeError` because this part of the code is not tested and I did not expect that it will be ever used. Guess I was wrong :smile_cat: 

I will add the test and verify that the code works as it should.

**Comment by aloejhb** [comment]
For a workaround, I removed the RuntimeError in this [line](https://github.com/fmi-basel/gfriedri-em-alignment/blob/2e41ff3b9330331b442544951c3e7ec6e0881ef4/src/sbem/record/Sample.py#L56) in Sample.py on the branch [bo-dev-v2](https://github.com/fmi-basel/gfriedri-em-alignment/tree/bo-dev-v2).
Allowing sections to be added in a permuted order will result in a sample.yaml with section entries that are not sorted.
For example:
```
- name: s300_g1
  section_num: 300
  tile_grid_num: 1
  acquisition: acq03
  stitched: false
  skip: false
  details: s300_g1/section.yaml
- name: s101_g1
  section_num: 101
  tile_grid_num: 1
  acquisition: acq02
  stitched: false
  skip: false
  details: s101_g1/section.yaml
```
Therefore I introduced sorting of sections before saving the sample.yaml.
This affect the following functions in Sample.py: [to_dict](https://github.com/fmi-basel/gfriedri-em-alignment/blob/2e41ff3b9330331b442544951c3e7ec6e0881ef4/src/sbem/record/Sample.py#L118), [_dump](https://github.com/fmi-basel/gfriedri-em-alignment/blob/2e41ff3b9330331b442544951c3e7ec6e0881ef4/src/sbem/record/Sample.py#L173) and [save](https://github.com/fmi-basel/gfriedri-em-alignment/blob/2e41ff3b9330331b442544951c3e7ec6e0881ef4/src/sbem/record/Sample.py#L189).
