### ISSUE TITLE
Expose min_range parameter for tile registration

### ISSUE THREAD

**Issue by aloejhb** [fmi-basel/gfriedri-em-alignment#33]
For some tiles with low contrast, it is useful to adjust the [min_range](https://github.com/google-research/sofima/blob/6052e2b54d3836b47732609baf09b259ed75add8/stitch_rigid.py#L70) parameter in sofima for successful stitching.
Therefore, it would be great to expose this parameter in the tile registration flow.

**Comment by tibuch** [comment]
Fix with tag v0.2.4.
