### ISSUE TITLE
Skip duplicated sections

### ISSUE THREAD

**Issue by TomasGancarcik** [fmi-basel/gfriedri-em-alignment#8]
Occasionally, there are duplicated sections in the data stack. They do not provide any additional valuable information for subsequent steps of the reconstruction pipeline. The feature should give a way of skipping those sections from aligning procedure.

**Comment by tibuch** [comment]
How should be decided which sections to skip? Should we add another parameter which is a list of section-IDs that should be skipped? That would probably be the easiest from a development point of view. However, is it possible to know beforehand which sections need to be skipped?

**Comment by aloejhb** [comment]
I think list of section-IDs to be skipped would already helpful. A major cause of section duplicates is that the block-face was not cut and the same section was imaged twice or more times. This kind of duplicates are noted manually by the microscope user during acquisition, and can therefore be known beforehand.
Other cases I am not sure, @TomasGancarcik  may have better ideas.

**Comment by TomasGancarcik** [comment]
In the first step, the list of sections to be skipped will be known beforehand. It can be simple text file with IDs of duplicates, or some other user editable file(s) within the SBEM project(s). In the future, we would like to run the alignment routine while the image acquisition is running and therefore a modified approach will be used.

**Comment by ganctom** [comment]
Feature implemented in the new workflow:
  1. Set section parameter 'skip' to True.
  2. Commit changes
  3. Run flow
